name: ci-test-py
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  py-pip-ai-sentryflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: check Python pip3 requirements
        run: |
          pip install -r requirements.txt
        working-directory: ai-engine

  py-ruff-ai-sentryflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ai-engine

      - name: Create pyproject.toml
        run: |
          echo "[tool.ruff.lint.per-file-ignores]" > pyproject.toml
          echo '"stringlifier/*" = ["E402", "F811", "F401"]' >> pyproject.toml
        working-directory: ai-engine

      - name: Lint with Ruff
        run: |
          pip install ruff
          ruff --output-format=github .
        working-directory: ai-engine

  py-lint-ai-sentryflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint
        working-directory: ai-engine

      - name: Lint with Pylint
        run: |
          pylint classifier.py
        working-directory: ai-engine

  py-pep8-ai-sentryflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Run PEP8'
        uses: quentinguidee/pep8-action@v1
        with:
          arguments: '--max-line-length=120 --exclude=*stringlifier/*,*protobuf/*'
